tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
# Cross-platform make
brew "cmake"

# Command-line fuzzy finder written in Go
brew "fzf"

# GNU compiler collection
brew "gcc"

# Search tool like grep and The Silver Searcher
brew "ripgrep"

# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"

# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"

# Cross-shell prompt for astronauts
brew "starship"

# Object-relational database system
brew "postgresql@14"

# Modern, maintained replacement for ls
brew "eza"

# Application uninstaller
cask "appcleaner"

# Developer targeted fonts with a high number of glyphs
cask "font-jetbrains-mono-nerd-font"

# Developer targeted fonts with a high number of glyphs
cask "font-symbols-only-nerd-font"

# GPU-accelerated cross-platform terminal emulator and multiplexer
cask "wezterm"

# Music streaming service
cask "spotify"
